language: php

notifications:
  email: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# allow builds against 7.0 and hhvm-nightly to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm-nightly

# faster builds when not using sudo
sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0"
  - travis_retry composer install --prefer-dist --no-interaction

  - travis_retry composer global require "codeception/codeception=2.0.*"
  - travis_retry composer global require "codeception/specify=*"
  - travis_retry composer global require "codeception/verify=*"

  - export GOPATH="$HOME/go"
  - export PATH="$GOPATH/bin:$PATH"
  - travis_retry go get github.com/Naktibalda/hhvm-serve

  - ./init --env=Development --overwrite=y

before_script:
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - mysql --version

  - mysql -e 'CREATE DATABASE `forum-tests`;';

  - |
    if [ $TRAVIS_PHP_VERSION = 'hhvm' ] || [ $TRAVIS_PHP_VERSION = 'hhvm-nightly' ]; then
      hhvm-serve --document-root=. --listen=127.0.0.1:8080 &
    else
      php -S 127.0.0.1:8080 &
    fi

script:
  - cd ./tests
  - ./codeception/bin/yii migrate --interactive=0
  - codecept build
  - codecept run

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = 'hhvm' ]; then
      killall hhvm-serve
    else
      killall php
    fi
